# Generated by Django 4.0.1 on 2022-03-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_world_rest_world_created_4b4a55_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=30)),
                ('world', models.CharField(max_length=16)),
                ('vocation', models.CharField(max_length=15)),
                ('level', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
