# Generated by Django 4.0.1 on 2022-03-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_highscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='exp',
            field=models.BigIntegerField(),
        ),
    ]
